[tool.poetry]
name = "kaggle-playground"
version = "0.1.0"
description = ""
authors = ["KazuSh1geru"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.52.2"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
